save wallet name & url
bitcoin-sv/spv-wallet-browser pull request #17
Opened 2024-10-27 16:50 UTC by Josh-121

2024-10-28 15:03 UTC, danwag06 requested changes
This looks good after the requested changes have been addressed. You can also clean up unnecessary code comments.

2024-10-28 15:03 UTC, danwag06 commented on src/utils/chromeStorageHelpers.ts
> +  chromeStorageService: any, // Accept as an argument
Use `ChromeStorageService` type here

2024-10-28 15:03 UTC, danwag06 commented on src/utils/chromeStorageHelpers.ts
> +      name: enteredAccountName,
use defaults here:
```
name: enteredAccountName || account.name,
icon: enteredAccountIcon || HOSTED_YOURS_IMAGE,
```

2024-10-28 18:41 UTC, danwag06 commented
This looks good @Josh-121 will get it merged at the completion of the hackathon. Nice work.

2024-10-28 18:54 UTC, Josh-121 commented
> This looks good @Josh-121 will get it merged at the completion of the hackathon. Nice work.

Thanks 🙏

2024-10-30 16:21 UTC, danwag06 approved these changes

2024-10-30 16:21 UTC, merged